server:
  port: 7001
spring:
  application:
    name: eureka-7001
eureka:
#  server:
#      evictionIntervalTimerInMs: 10000
  instance:
    hostname: eureka-7001   #eureka服务端的实例名称
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己
    fetch-registry: false   #false表示自己端就是注册中心
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   #单机
      defaultZone: http://localhost:${server.port}/eureka/   #单机