server:
    port: 8002
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
  #      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: dept-consumer
    prefer-ip-address: true     #访问路径可以显示IP地址
feign:
  hystrix:
      enabled: true
  compression:
      request:
          mime-types: # 可以被压缩的类型
              - text/xml
              - application/xml
              - application/json
          min-request-size: 2048 # 超过2048的字节进行压缩
logging:
  level:
    com.jeffcode.consumerdept8002.service: DEBUG
spring:
  application:
    name: microservicecloud-dept-consumer
turbine:
  app-config: MICROCLOUD-PROVIDER-COMPANY,MICROSERVICECLOUD-DEPT,microservicecloud-dept-consumer # 定义所有要监控的微服务信息
  cluster-name-expression: new String("default") # 设置监控的表达式，通过此表达式表示要获取监控信息名称